version: '3.7'

services:
  database:
    image: postgres
    container_name: database_ignite_delivery
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=delivery_project
      - POSTGRES_DB=deliveries
    volumes: 
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local